name: BALcanOSH.net
favicon: null
layout_spectrum: 0.4693448774050921
typography_spectrum: 0.19730527140200138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3125
  lightness: 0.2171487221494317
  saturation: 0.03239291161298752
  rhythmicContrast: 0.7247730698436499
purpose: []
