name: BALcanOSH.net
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05597
title: Balkan Occupational Safety and Health Movement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72925434-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
