name: BALcanOSH.net
favicon: null
layout_spectrum: 0.39322
typography_spectrum: 0.06447
title: Regional Professional Balkan Occupational Safety and Health Movement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.2171487221494317
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
