title: Balkan Occupational Safety and Health Movement
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.6810036
  lightness: 0.5
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-72925434-1
  facebook: null
favicon: null
name: BALcanOSH.net
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.890681
layout_spectrum: 1
